### ISSUE TITLE
FileopenPicker (UWP) throws error when PickSingleFileAsync() called

### ISSUE THREAD

**Issue by jasells** [jamesmcroft/XPlat-Windows-APIs#23]
"WinRT information: The FileTypeFilters property must have at least one file type filter specified."

There is no way to *set* the filter... it is read only, and not virtual.

[FileOpenPicker.cs](https://github.com/jamesmcroft/XPlat-Windows-APIs/blob/develop/XPlat.Storage.UWP/Pickers/FileOpenPicker.cs)

Am I missing some other initialization step?

**Comment by jamesmcroft** [comment]
You can add file type filters like so:

```csharp
var singleFilePick = new FileOpenPicker(this);
            singleFilePick.FileTypeFilter.Add(".jpg");

var pickedFile = await singleFilePick.PickSingleFileAsync();
```

Let me know if this solves your issue.

**Comment by jasells** [comment]
Duh, I’m being dense… thank you.  End of a long day...

**Comment by jasells** [comment]
James,
 maybe you have some more insight into a problem I'm having now... have you used this code on UWP, or only on Droid/iOS?

I am trying to open a file on UWP, but keep getting error stating file does not exists.  I *think* the source is line#62 here: [StorageFile.cs](https://github.com/jamesmcroft/XPlat-Windows-APIs/blob/develop/XPlat.Storage.UWP/StorageFile.cs)

I would expect SystemIO.File.Exists() to work on Dorid/iOS, but not UWP (always returns false due to difference in sec vs. desktop API on windows).

I am interested in using several of your libs with Xamarin.Forms to support multiplatform, but I suspect you have not designed for use on UWP.

**Comment by jasells** [comment]
I have proven that the issue *is* with File.Exists() on UWP.  It no work like expected =( .  Sad that .NetStandard provides an API that doesn't behave... but that's why we have the PCL mess we have … anyway, that's a different topic.

If you were to replace line #62 in [StorageFile.cs](https://github.com/jamesmcroft/XPlat-Windows-APIs/blob/develop/XPlat.Storage.UWP/StorageFile.cs) 
`public bool Exists => this.Originator != null && File.Exists(this.Path);`

with something like:
`public bool Exists => this.Originator != null && CheckFileExists(this.Path);`
.
.
.
`protected virtual bool CheckFileExists(string path) => File.Exists(this.Path)`

I could then provide a different impl for UWP.   Is supect there is similar code in [StorageFolder.cs](https://github.com/jamesmcroft/XPlat-Windows-APIs/blob/develop/XPlat.Storage.UWP/StorageFolder.cs)  (line 65)

**Comment by jamesmcroft** [comment]
@jasells I will take a look into this. It has previously been working but as you've mentioned, changes in .NET Standard may have broken this and as you've pointed out, this is because File.Exists doesn't work if the file in UWP is outside of the scope of the application's storage location.

**Comment by jasells** [comment]
The only way I've been able to accomplish the File.Exists fuctionality (even in a pure UWP app) is to do something like:

`public async Task<System.IO.Stream> OpenFileForRead(XPlat.Storage.IStorageFile file)
        {
            var dir = await file.GetParentAsync();
            Windows.Storage.IStorageFile nativeFile;
            Windows.Storage.IStorageFolder parentDir = null;

            if (dir.Path.ToLower().Contains("c:"))
            {
               //check all the known folders
            }
            else //it is removable drive
            {
                var fldrs = (await Windows.Storage.KnownFolders.RemovableDevices.GetFoldersAsync()).ToList();

                parentDir = fldrs.FirstOrDefault(fldr => fldr.Name == dir.Name);

                var name = parentDir.Name;
            }

            nativeFile = (await parentDir.GetItemAsync(file.Name)) as Windows.Storage.IStorageFile;

            return (await nativeFile.OpenReadAsync()).AsStream();
        }`

This is basically what I did using Xamarin's Dependency service to provide a plugin, and then I used an extension method in my portable code to add it back to Xplat.Storage.IStorageFile and just not using  OpenReadAsync() provided.

It *might* be more a function of the target/min UWP version, not .NetStandard, if you say it has been working?  I am targeting min of 1709 (SDK v. 16299).

**Comment by jasells** [comment]
I think the appropriate thing to do here is close this issue, and open a new one with a more appropriate title/focus.
