### ISSUE TITLE
Port to .NET Standard

### ISSUE THREAD

**Issue by jamesmcroft** [jamesmcroft/XPlat-Windows-APIs#26]
With .NET standard maturing, it's time to port XPlat Windows APIs to the platform.

**Comment by tom-made** [comment]
@jamesmcroft where are we with this?

**Comment by jamesmcroft** [comment]
I think this might be complete now @tom-made but I need to verify. Everything I've done has been ported but I might want to make a change to bring components back in that were removed due to no longer being used. However, I think the corrective cause would be to tag them as deprecated rather than ripping them straight out right now. We will remove them in a future release.

**Comment by jamesmcroft** [comment]
@tom-made I think I'm happy with this to go now but happy for you to test more.

**Comment by tom-made** [comment]
This all seems good. Will close this off now.
