### ISSUE TITLE
CameraCaptureUI doesn't inform the user that they cancelled permissions

### ISSUE THREAD

**Issue by jamesmcroft** [jamesmcroft/XPlat-Windows-APIs#29]
When accessing the CameraCaptureUI API, the user will be asked for the first time if they would like to grant permissions for photo/video.

Pressing deny will return a result as if the user had not captured a photo/cancelled out of the activity.

It would be more ideal for the result of the activity to inform that the permissions were denied to allow a differentiation between cancellation.

**Comment by tom-made** [comment]
I'll close this off for you @jamesmcroft. As I mentioned in the comment of the PR, can we look at fleshing out the sample app?
