### ISSUE TITLE
Implement Windows.UI.Color

### ISSUE THREAD

**Issue by jamesmcroft** [jamesmcroft/XPlat-Windows-APIs#41]
This API will be an implementation of the Windows Color struct, however, will need to be compatible with the System Color struct also.

**Comment by tom-made** [comment]
Will this API also be compatible with platform specific Colors? This would come in handy when trying to assign them in iOS or Android specific code to controls for example.

**Comment by tom-made** [comment]
I've assigned this to you @jamesmcroft, looks like you've done the work already

**Comment by tom-made** [comment]
Closing this off with PR #44.
